blank_issues_enabled: false
contact_links:
  - name: NoFeelCaptcha source repository
    url: https://github.com/NoFeelCaptcha/nofeel-k8s/issues
    about: Report source and application issues in the source repository.
